services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=punchedBackend'
      - 'MONGO_INITDB_ROOT_PASSWORD=NiVETL5knrezxW'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=punchedBackend'
      - 'MYSQL_USER=punchedAdmin'
      - 'MYSQL_PASSWORD=NiVETL5knrezxW'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  elasticsearch:
    image: 'elasticsearch:7.17.10'
    networks:
      - elastic
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
  kibana:
    image: 'kibana:7.17.10'
    networks:
      - elastic
    ports:
      - '5601:5601'
networks:
  elastic:
    driver: 'bridge'